In [2]:
import pandas as py
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
data = sns.load_dataset("titanic")
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [17]:
data = data.iloc[:,8:]
data.head()

   class    who  adult_male deck  embark_town alive  alone
0  Third    man        True  NaN  Southampton    no  False
1  First  woman       False    C    Cherbourg   yes  False
2  Third  woman       False  NaN  Southampton   yes   True
3  First  woman       False    C  Southampton   yes  False
4  Third    man        True  NaN  Southampton    no   True

In [24]:
from sklearn.model_selection import train_test_split

X = data.iloc[:, 0]
y = data.iloc[:, 6]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
X_train

331     First
733    Second
382     Third
704     Third
813     Third
        ...
106     Third
270     First
860     Third
435     First
102     First
Name: class, Length: 712, dtype: category
Categories (3, object): ['First', 'Second', 'Third']

In [ ]:
from sklearn.preprocessing import ordinaleencoder